### PR TITLE
added seo meetup to meetups

### PR DESCRIPTION
**Pull request by mattzipan**
Hi Kevin,
following up on yesterday, I added the seo meetup in the meetups:

Not sure how to update the json holding the next events though:
https://cphcomevents.storage.googleapis.com/events.json

hope this is all good

PS: first pull request  🍾

### CODE REVIEW

**Comment by mattzipan** [comment]
@kevinsimper is this okay?

**Comment by kevinsimper** [comment]
Hi @mattzipan, sorry I didn't see it, I hadn't watched my own repo so thank you for tagging me! 👏

Fedt du har fundet billede og det hele, kan se der er en conflict, men skal nok lige få det resolved 😄

**Comment by mattzipan** [comment]
oh sorry, den conflict har ikke været der en måned siden, der jeg sendte min pull request. 🤷‍♂️. Sig til, hvis der ellers mangler noget :)

**Comment by kevinsimper** [comment]
@mattzipan Yeah, it was me who made it conflict, I resolved it and it is merged here 😄https://github.com/kevinsimper/copenhagen.community/commit/8733681fbe187c8d7a29a3c637da753e52001001

I also deployed the cloud function that updates the `events.json`, so your event appears now! 🎉

**Comment by mattzipan** [comment]
AWESOME! mange tak!

**Pull request closed without merging**
