### PR TITLE
Add LaravelCph meetup

### PR DESCRIPTION
**Pull request by prazian**
This PR adds LaravelCPH Meetup to the `copenhagen.community` website.

### CODE REVIEW

**Comment by kevinsimper** [comment]
Hi @prazian 

Awesome adding the meetup 😄

image

Can you find a architectical picture from copenhagen so that it matches the others? https://unsplash.com/s/photos/copenhagen

**Comment by prazian** [comment]
Hey @kevinsimper 
Thanks for your prompt feedback. 😎 
I changed the background photo to match the other ones. 🙂

**Comment by kevinsimper** [comment]
Great! 😄

It looks great, thanks for adding it! The events should show up now!

**Comment by prazian** [comment]
Thanks @kevinsimper for accepting the PR to add LaravelCPH meetup. 🙂

**Pull request merged**
